services:
  proxy:
    image: nginx:1.25.3-alpine
    container_name: proxy
    volumes:
      - ./nginx/docker/nginx.conf:/etc/nginx/templates/nginx.conf.template
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    ports:
      - '80:80'
    command: [ nginx-debug, '-g', 'daemon off;' ]
    logging:
      driver: local
  cms:
    image: cms:latest
    container_name: cms
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    command: [ nginx-debug, '-g', 'daemon off;' ]
    logging:
      driver: local
  site:
    image: site:latest
    container_name: site
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    command: [ nginx-debug, '-g', 'daemon off;' ]
    logging:
      driver: local
