services:
  backend:
    image: backend:latest
    container_name: backend
    profiles: [ full ]

  frontend:
    image: frontend:latest
    container_name: frontend
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    command: [nginx-debug, '-g', 'daemon off;']
    logging:
      driver: local
    depends_on:
      - backend
    profiles: [full]

  proxy:
    image: nginx:1.25.3-alpine
    container_name: proxy
    volumes:
      - ./proxy/docker/nginx.conf:/etc/nginx/templates/nginx.conf.template
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    ports:
      - '80:80'
    command: [nginx-debug, '-g', 'daemon off;']
    logging:
      driver: local
    extra_hosts:
      - "host.docker.internal:host-gateway"

  e2e:
    network_mode: 'host'
    image: e2e
    depends_on:
      - proxy
      - frontend
      - backend
    container_name: e2e
    profiles: [e2e]
