services:
  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    ports:
      - '80:80'
    command: [ nginx-debug, '-g', 'daemon off;' ]
    logging:
      driver: local
