
services:
  proxy:
    image: nginx:1.25.3-alpine
    container_name: proxy
    volumes:
      - ./nginx/docker/nginx.conf:/etc/nginx/templates/nginx.conf.template
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    ports:
      - '80:80'
    command: [nginx-debug, '-g', 'daemon off;']
    logging:
      driver: local
    healthcheck:
      test: curl http://localhost
      start_period: 10s
      interval: 10s
      retries: 3

  backend:
    image: backend:latest
    container_name: backend
    depends_on:
      - mssql
      - proxy
    profiles: [full]

  mssql:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Change_Password"
      ACCEPT_EULA: "Y"

  frontend:
    image: frontend:latest
    container_name: frontend
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    command: [nginx-debug, '-g', 'daemon off;']
    logging:
      driver: local
    depends_on:
      - backend
    profiles: [full]

  e2e:
    image: e2e
    depends_on:
      proxy:
        condition: service_healthy
    container_name: e2e
    volumes:
      - ../e2e/:/e2e
    environment:
      - BASE_URL=http://proxy/
    profiles: [e2e]
