name: Actions test
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.6.0
      - name: Setup docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Install dependencies
        run: pnpm install
      - name: Run checks
        run: pnpm run "/^check:.*/"
      - name: Run tests
        run: pnpm run -r "/^test.*/"
      - name: Build apps
        run: pnpm run -r "/^build.*/"

  e2e:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v4
      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ./docker-compose.yml
      - name: Run E2E
        run: docker compose --profile full --profile e2e up --attach e2e --exit-code-from=e2e
