name: Actions test
on: [push]
jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.6.0
      - name: Install dependencies
        run: pnpm install
      - name: Run checks
        run: pnpm run "/^check:.*/"
      - name: Run tests
        run: pnpm run -r "/^test.*/"
      - name: Run build
        run: pnpm run -r "/^build.*/"

  e2e:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - uses: actions/checkout@v3
      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: ./docker-compose.yml
      - name: Run E2E
        run: docker compose --profile full --profile e2e up --exit-code-from=e2e
