name: Actions test
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.6.0
      - name: Install dependencies
        run: pnpm install
      - name: Run checks
        run: pnpm run "/^check:.*/"
      - name: Run tests
        run: pnpm run -r "/^test.*/"

  e2e:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v4
      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: './docker/docker-compose.yml'
      - name: Run E2E
        run: docker compose --profile full --profile e2e up --exit-code-from=e2e
