name: Actions test
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.4.0
      - name: Install dependencies
        run: npm ci
      - name: Run prettier
        run: npm run check:prettier
      - name: Run eslint
        run: npm run check:eslint

  build-backend:
    runs-on: ubuntu-latest
    needs: check
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.4.0
      - name: Install dependencies
        run: npm ci
      - name: Test backend
        run: npm run test
      - name: Build backend
        run: npm run build

  build-frontend:
    runs-on: ubuntu-latest
    needs: check
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.4.0
      - name: Install dependencies
        run: npm ci
      - name: Build frontend
        run: npm run build

  e2e:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
    - uses: actions/checkout@v3
    - uses: adambirds/docker-compose-action@v1.3.0
      with:
        compose-file: "./docker/docker-compose.yml"
